name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12] 

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Django
      run: |
        python -m pip install --upgrade pip
        python -m pip install django

    - name: Run unit tests and Integration tests 
      run: |
         run: python manage.py test backend_app


    - name: Lint code with Flake8
      run: |
        python -m pip install flake8
        flake8 .

    - name: Format code with Black
      run: |
        python -m pip install black
        black . --check
