name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django
          pip install djangorestframework

      - name: Prepare database
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Flake8 linting
        run: |
          pip install flake8
          pip install black
          black .
          flake8 --max-line-length=120 .

      - name: Run Black code formatting check
        run: |
          pip install black
          black --check .

      - name: Run unit tests and Integrations
        run: python manage.py test backend_app

